language: python
python:
  - "3.5"
before_install:
  - sudo apt-get update
  - sudo apt-get install -qq gir1.2-gdkpixbuf-2.0, gir1.2-glib-2.0, gir1.2-gtk-3.0, gir1.2-pango-1.0, gir1.2-webkit2-4.0, python3-enchant, python3-gi, python3-pip, python3-yaml
virtualenv:
  system_site_packages: false
env:
  - TOXENV=py35
install:
  - pip3 install tox
script:
  - tox
