sudo: required

language: python

services:
  - docker

before_install:
# keep container running (https://stackoverflow.com/questions/30209776)
- docker run -d --name app ubuntu tail -f /dev/null
- docker ps -a

script:
- docker ps -a
- docker exec app apt-get update
- docker exec app pwd
- docker exec app find .
- docker exec app apt-get install -qq gir1.2-gdkpixbuf-2.0 gir1.2-glib-2.0 gir1.2-gtk-3.0 gir1.2-pango-1.0 gir1.2-webkit2-4.0 git python3 python3-enchant python3-gi python3-pip python3-yaml
- docker exec app pip3 install -U pip tox

after_script:
- docker rm -f app
